name: object_detection_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.5
  tflite_flutter: ^0.11.0
  image: ^4.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
